# tomcat properties
server:
  context-path: /activity
  port: 8091
  tomcat:
    basedir: ${user.home}/deployer/tomcat

# DataSource and JPA Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.141.210:3306/activity?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: classpath:mapper/*.xml

flyway:
  baseline-on-migrate: true

logging:
  level:
    org.springframework.web: warn
    com.activity: info

