# tomcat properties
server:
  context-path: /activity
  port: 8080

# DataSource and JPA Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/activity?useUnicode\=true&ampcharacterEncoding\=utf-8
    username: postgres
    password: Teamw0rk
    test-on-borrow: true
    validation-query: SELECT 1;
    validation-interval: 30000
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 60
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true

logging:
  level:
    org.springframework.web: DEBUG
    com.wx.activity: DEBUG

wechat:
  mp:
    appId: 1
    secret: 1
    token: 1
    aesKey: 1