# tomcat properties
server:
  context-path: /activity
  port: 8099

# DataSource and JPA Configuration
spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/activity?useUnicode\=true&ampcharacterEncoding\=utf-8
#    username: postgres
#    password: Teamw0rk
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.141.210:3306/activity?useUnicode\=true&ampcharacterEncoding\=utf-8
    username: root
    password: 123456
#    test-on-borrow: true
#    validation-query: SELECT 1;
#    validation-interval: 30000
#    test-while-idle: true
#    time-between-eviction-runs-millis: 60000
#    remove-abandoned: true
#    remove-abandoned-timeout: 60
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
#    database: postgresql
    database: mysql
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true

logging:
  level:
    org.springframework.web: DEBUG
    com.wx.activity: DEBUG

wechat:
  mp:
    appId: wx84a8649ef7a1171d
    secret: 7082b585c84f6b346fe9478ebfe7f382
    token: weixin
    aesKey: rKoI4DFAJZgYNv5ol2eHF6rvEY5uJbq8WHD7eVcPjHy