# tomcat properties
server:
  context-path: /activity
  port: 8081

# DataSource and JPA Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.141.210:3306/activity?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework.web: warn
    com.activity: debug

wechat:
  uri: http://tt.51meiy.com
  mp:
    appId: wx84a8649ef7a1171d
    secret: 7082b585c84f6b346fe9478ebfe7f382
    token: weixin
    aesKey: rKoI4DFAJZgYNv5ol2eHF6rvEY5uJbq8WHD7eVcPjHy